-- =============================================================================
-- V1 — Create the companies table in the 'company' schema.
--
-- The Company Service owns this schema exclusively.  No other service may
-- read from or write to it directly; all cross-service access goes through
-- the Company Service REST API or Kafka events.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS company;

CREATE TABLE IF NOT EXISTS company.companies (
    id            VARCHAR(36)  NOT NULL,
    name          VARCHAR(200) NOT NULL,
    type          VARCHAR(10)  NOT NULL CHECK (type IN ('SHIPPER', 'CARRIER', 'BOTH')),
    status        VARCHAR(10)  NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE', 'PENDING')),
    tax_id        VARCHAR(50),
    contact_name  VARCHAR(200),
    contact_email VARCHAR(200),
    contact_phone VARCHAR(50),
    notes         TEXT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_companies PRIMARY KEY (id),
    CONSTRAINT uq_companies_name UNIQUE (name)
);

-- Index for status-based filtering (most common query pattern)
CREATE INDEX IF NOT EXISTS idx_companies_status ON company.companies (status);

-- Index for name search
CREATE INDEX IF NOT EXISTS idx_companies_name_lower ON company.companies (LOWER(name));

COMMENT ON TABLE  company.companies              IS 'Logistics company aggregate root — managed exclusively by Company Service';
COMMENT ON COLUMN company.companies.id           IS 'UUID primary key generated by the application layer';
COMMENT ON COLUMN company.companies.type         IS 'SHIPPER: ships goods; CARRIER: transports goods; BOTH: does both';
COMMENT ON COLUMN company.companies.status       IS 'ACTIVE: operational; INACTIVE: suspended; PENDING: awaiting approval';
