package com.logistics.ui.theme;

/**
 * Generates the application's master CSS stylesheet as a data URI string.
 *
 * JavaFX supports loading stylesheets from URLs. By generating the CSS
 * programmatically here we avoid a separate resource file and keep the
 * design tokens in sync with the CSS variables automatically.
 *
 * Usage:
 *   scene.getStylesheets().add(AppStylesheet.toDataUri());
 *
 * The stylesheet uses JavaFX CSS syntax (prefixed with -fx-) for all
 * JavaFX-specific properties, alongside standard CSS for layout hints
 * that JavaFX CSS also understands (padding, spacing, etc.).
 */
public final class AppStylesheet {

    private AppStylesheet() {}

    /**
     * Returns the full stylesheet content as a JavaFX-compatible data URI.
     * Call this once during application startup and add to every Scene.
     */
    public static String toDataUri() {
        String css = buildCss();
        // JavaFX requires the stylesheet to be presented as a URL.
        // The "data:" URI scheme is supported for inline stylesheets.
        String encoded = java.util.Base64.getEncoder()
                .encodeToString(css.getBytes(java.nio.charset.StandardCharsets.UTF_8));
        return "data:text/css;base64," + encoded;
    }

    // -------------------------------------------------------------------------
    // CSS Builder
    // -------------------------------------------------------------------------

    private static String buildCss() {
        final String p900 = DesignTokens.CSS_PRIMARY_900;
        final String p800 = DesignTokens.CSS_PRIMARY_800;
        final String p700 = DesignTokens.CSS_PRIMARY_700;
        final String p600 = DesignTokens.CSS_PRIMARY_600;
        final String p400 = DesignTokens.CSS_PRIMARY_400;
        final String p100 = DesignTokens.CSS_PRIMARY_100;
        final String p050 = DesignTokens.CSS_PRIMARY_050;

        final String n900 = DesignTokens.CSS_NEUTRAL_900;
        final String n700 = DesignTokens.CSS_NEUTRAL_700;
        final String n500 = DesignTokens.CSS_NEUTRAL_500;
        final String n300 = DesignTokens.CSS_NEUTRAL_300;
        final String n100 = DesignTokens.CSS_NEUTRAL_100;
        final String n000 = DesignTokens.CSS_NEUTRAL_000;

        final String succ600 = DesignTokens.CSS_SUCCESS_600;
        final String succ100 = DesignTokens.CSS_SUCCESS_100;
        final String warn600 = DesignTokens.CSS_WARNING_600;
        final String warn100 = DesignTokens.CSS_WARNING_100;
        final String dang600 = DesignTokens.CSS_DANGER_600;
        final String dang100 = DesignTokens.CSS_DANGER_100;
        final String info600 = DesignTokens.CSS_INFO_600;
        final String info100 = DesignTokens.CSS_INFO_100;

        return """
                /* ==========================================================
                   LOGISTICS MANAGEMENT SYSTEM — MASTER STYLESHEET
                   Generated by AppStylesheet.java
                   ========================================================== */

                /* ----------------------------------------------------------
                   ROOT / SCENE
                   ---------------------------------------------------------- */
                .root {
                    -fx-font-family: "Inter", "Segoe UI", "System";
                    -fx-font-size: 14px;
                    -fx-background-color: %s;
                }

                /* ----------------------------------------------------------
                   SIDEBAR NAVIGATION
                   ---------------------------------------------------------- */
                .sidebar {
                    -fx-background-color: %s;
                    -fx-min-width: 240px;
                    -fx-pref-width: 240px;
                }

                .sidebar-collapsed {
                    -fx-min-width: 64px;
                    -fx-pref-width: 64px;
                }

                .sidebar-logo-area {
                    -fx-background-color: %s;
                    -fx-min-height: 64px;
                    -fx-pref-height: 64px;
                    -fx-alignment: center-left;
                    -fx-padding: 0 16px;
                }

                .sidebar-logo-text {
                    -fx-text-fill: white;
                    -fx-font-size: 15px;
                    -fx-font-weight: bold;
                }

                .sidebar-section-label {
                    -fx-text-fill: %s;
                    -fx-font-size: 11px;
                    -fx-font-weight: bold;
                    -fx-padding: 16px 16px 4px 16px;
                }

                .nav-item {
                    -fx-background-color: transparent;
                    -fx-text-fill: derive(white, -20%%);
                    -fx-font-size: 14px;
                    -fx-alignment: center-left;
                    -fx-padding: 0 16px;
                    -fx-min-height: 48px;
                    -fx-pref-height: 48px;
                    -fx-cursor: hand;
                    -fx-background-radius: 0;
                    -fx-border-color: transparent;
                }

                .nav-item:hover {
                    -fx-background-color: %s;
                    -fx-text-fill: white;
                }

                .nav-item-active {
                    -fx-background-color: %s;
                    -fx-text-fill: white;
                    -fx-font-weight: bold;
                    -fx-border-color: transparent transparent transparent %s;
                    -fx-border-width: 0 0 0 3px;
                }

                /* ----------------------------------------------------------
                   TOP APPLICATION BAR
                   ---------------------------------------------------------- */
                .topbar {
                    -fx-background-color: %s;
                    -fx-min-height: 56px;
                    -fx-pref-height: 56px;
                    -fx-border-color: transparent transparent %s transparent;
                    -fx-border-width: 0 0 1px 0;
                    -fx-effect: dropshadow(gaussian, rgba(0,0,0,0.08), 4, 0, 0, 1);
                    -fx-padding: 0 24px;
                }

                .topbar-breadcrumb {
                    -fx-text-fill: %s;
                    -fx-font-size: 14px;
                }

                .topbar-breadcrumb-active {
                    -fx-text-fill: %s;
                    -fx-font-weight: bold;
                }

                /* ----------------------------------------------------------
                   GLOBAL SEARCH FIELD
                   ---------------------------------------------------------- */
                .global-search {
                    -fx-background-color: %s;
                    -fx-border-color: %s;
                    -fx-border-radius: 6px;
                    -fx-background-radius: 6px;
                    -fx-border-width: 1.5px;
                    -fx-pref-width: 320px;
                    -fx-min-height: 36px;
                    -fx-pref-height: 36px;
                    -fx-padding: 0 12px;
                    -fx-font-size: 14px;
                    -fx-text-fill: %s;
                    -fx-prompt-text-fill: %s;
                }

                .global-search:focused {
                    -fx-border-color: %s;
                    -fx-effect: dropshadow(gaussian, rgba(46,109,164,0.20), 4, 0, 0, 0);
                }

                /* ----------------------------------------------------------
                   PAGE CONTENT AREA
                   ---------------------------------------------------------- */
                .content-area {
                    -fx-background-color: %s;
                    -fx-padding: 24px;
                }

                .page-title {
                    -fx-font-size: 22px;
                    -fx-font-weight: bold;
                    -fx-text-fill: %s;
                }

                .section-title {
                    -fx-font-size: 15px;
                    -fx-font-weight: bold;
                    -fx-text-fill: %s;
                }

                /* ----------------------------------------------------------
                   CARD / PANEL
                   ---------------------------------------------------------- */
                .card {
                    -fx-background-color: %s;
                    -fx-background-radius: 8px;
                    -fx-border-color: %s;
                    -fx-border-radius: 8px;
                    -fx-border-width: 1px;
                    -fx-effect: dropshadow(gaussian, rgba(0,0,0,0.08), 6, 0, 0, 2);
                    -fx-padding: 20px;
                }

                /* ----------------------------------------------------------
                   KPI / METRIC CARD
                   ---------------------------------------------------------- */
                .kpi-card {
                    -fx-background-color: %s;
                    -fx-background-radius: 8px;
                    -fx-border-color: %s;
                    -fx-border-radius: 8px;
                    -fx-border-width: 1px;
                    -fx-effect: dropshadow(gaussian, rgba(0,0,0,0.08), 6, 0, 0, 2);
                    -fx-padding: 20px 20px;
                    -fx-min-height: 100px;
                    -fx-pref-height: 100px;
                }

                .kpi-label {
                    -fx-text-fill: %s;
                    -fx-font-size: 12px;
                    -fx-font-weight: normal;
                }

                .kpi-value {
                    -fx-text-fill: %s;
                    -fx-font-size: 28px;
                    -fx-font-weight: bold;
                }

                .kpi-trend-positive {
                    -fx-text-fill: %s;
                    -fx-font-size: 12px;
                }

                .kpi-trend-negative {
                    -fx-text-fill: %s;
                    -fx-font-size: 12px;
                }

                /* ----------------------------------------------------------
                   BUTTONS
                   ---------------------------------------------------------- */
                .btn-primary {
                    -fx-background-color: %s;
                    -fx-text-fill: white;
                    -fx-font-size: 14px;
                    -fx-font-weight: 600;
                    -fx-padding: 10px 20px;
                    -fx-background-radius: 6px;
                    -fx-cursor: hand;
                    -fx-border-color: transparent;
                }

                .btn-primary:hover {
                    -fx-background-color: %s;
                }

                .btn-primary:pressed {
                    -fx-background-color: %s;
                }

                .btn-primary:disabled {
                    -fx-background-color: %s;
                    -fx-text-fill: %s;
                    -fx-cursor: default;
                }

                .btn-secondary {
                    -fx-background-color: transparent;
                    -fx-text-fill: %s;
                    -fx-font-size: 14px;
                    -fx-font-weight: 600;
                    -fx-padding: 9px 20px;
                    -fx-background-radius: 6px;
                    -fx-border-color: %s;
                    -fx-border-width: 1.5px;
                    -fx-border-radius: 6px;
                    -fx-cursor: hand;
                }

                .btn-secondary:hover {
                    -fx-background-color: %s;
                }

                .btn-danger {
                    -fx-background-color: %s;
                    -fx-text-fill: white;
                    -fx-font-size: 14px;
                    -fx-font-weight: 600;
                    -fx-padding: 10px 20px;
                    -fx-background-radius: 6px;
                    -fx-cursor: hand;
                }

                .btn-icon {
                    -fx-background-color: transparent;
                    -fx-text-fill: %s;
                    -fx-min-width: 36px;
                    -fx-min-height: 36px;
                    -fx-pref-width: 36px;
                    -fx-pref-height: 36px;
                    -fx-background-radius: 6px;
                    -fx-padding: 0;
                    -fx-cursor: hand;
                    -fx-alignment: center;
                }

                .btn-icon:hover {
                    -fx-background-color: %s;
                }

                /* ----------------------------------------------------------
                   FORM CONTROLS
                   ---------------------------------------------------------- */
                .form-label {
                    -fx-text-fill: %s;
                    -fx-font-size: 11px;
                    -fx-font-weight: bold;
                }

                .form-input {
                    -fx-background-color: %s;
                    -fx-border-color: %s;
                    -fx-border-radius: 4px;
                    -fx-background-radius: 4px;
                    -fx-border-width: 1.5px;
                    -fx-min-height: 40px;
                    -fx-pref-height: 40px;
                    -fx-padding: 0 12px;
                    -fx-font-size: 14px;
                    -fx-text-fill: %s;
                    -fx-prompt-text-fill: %s;
                }

                .form-input:focused {
                    -fx-border-color: %s;
                }

                .form-input-error {
                    -fx-border-color: %s;
                }

                .form-error-text {
                    -fx-text-fill: %s;
                    -fx-font-size: 12px;
                }

                .form-combo {
                    -fx-background-color: %s;
                    -fx-border-color: %s;
                    -fx-border-radius: 4px;
                    -fx-background-radius: 4px;
                    -fx-border-width: 1.5px;
                    -fx-min-height: 40px;
                    -fx-pref-height: 40px;
                    -fx-padding: 0 12px;
                    -fx-font-size: 14px;
                }

                .form-combo:focused {
                    -fx-border-color: %s;
                }

                /* ----------------------------------------------------------
                   DATA TABLE
                   ---------------------------------------------------------- */
                .data-table {
                    -fx-background-color: %s;
                    -fx-border-color: %s;
                    -fx-border-radius: 8px;
                    -fx-background-radius: 8px;
                }

                .data-table .column-header {
                    -fx-background-color: %s;
                    -fx-text-fill: %s;
                    -fx-font-size: 11px;
                    -fx-font-weight: bold;
                    -fx-min-height: 40px;
                    -fx-pref-height: 40px;
                    -fx-padding: 0 16px;
                }

                .data-table .column-header-background {
                    -fx-background-color: %s;
                }

                .data-table .table-row-cell {
                    -fx-background-color: %s;
                    -fx-min-height: 48px;
                    -fx-pref-height: 48px;
                    -fx-border-color: transparent transparent %s transparent;
                    -fx-border-width: 0 0 1px 0;
                }

                .data-table .table-row-cell:odd {
                    -fx-background-color: %s;
                }

                .data-table .table-row-cell:hover {
                    -fx-background-color: %s;
                }

                .data-table .table-row-cell:selected {
                    -fx-background-color: %s;
                    -fx-border-color: transparent transparent %s %s;
                    -fx-border-width: 0 0 1px 3px;
                }

                .data-table .table-cell {
                    -fx-text-fill: %s;
                    -fx-font-size: 14px;
                    -fx-padding: 0 16px;
                    -fx-alignment: center-left;
                }

                /* ----------------------------------------------------------
                   STATUS BADGES
                   ---------------------------------------------------------- */
                .badge {
                    -fx-padding: 4px 10px;
                    -fx-background-radius: 9999px;
                    -fx-font-size: 12px;
                    -fx-font-weight: bold;
                }

                .badge-delivered {
                    -fx-background-color: %s;
                    -fx-text-fill: %s;
                }

                .badge-in-transit {
                    -fx-background-color: %s;
                    -fx-text-fill: %s;
                }

                .badge-pending {
                    -fx-background-color: %s;
                    -fx-text-fill: %s;
                }

                .badge-overdue {
                    -fx-background-color: %s;
                    -fx-text-fill: %s;
                }

                .badge-cancelled {
                    -fx-background-color: %s;
                    -fx-text-fill: %s;
                }

                .badge-active {
                    -fx-background-color: %s;
                    -fx-text-fill: %s;
                }

                .badge-inactive {
                    -fx-background-color: %s;
                    -fx-text-fill: %s;
                }

                /* ----------------------------------------------------------
                   DIALOG / MODAL OVERLAY
                   ---------------------------------------------------------- */
                .modal-overlay {
                    -fx-background-color: rgba(0, 0, 0, 0.5);
                }

                .modal-dialog {
                    -fx-background-color: %s;
                    -fx-background-radius: 12px;
                    -fx-border-color: %s;
                    -fx-border-radius: 12px;
                    -fx-border-width: 1px;
                    -fx-effect: dropshadow(gaussian, rgba(0,0,0,0.22), 32, 0, 0, 8);
                    -fx-padding: 28px;
                }

                .modal-title {
                    -fx-font-size: 18px;
                    -fx-font-weight: bold;
                    -fx-text-fill: %s;
                }

                .modal-divider {
                    -fx-background-color: %s;
                    -fx-min-height: 1px;
                    -fx-pref-height: 1px;
                    -fx-max-height: 1px;
                }

                /* ----------------------------------------------------------
                   NOTIFICATION TOAST
                   ---------------------------------------------------------- */
                .toast {
                    -fx-background-color: %s;
                    -fx-background-radius: 8px;
                    -fx-border-radius: 8px;
                    -fx-effect: dropshadow(gaussian, rgba(0,0,0,0.22), 16, 0, 0, 4);
                    -fx-pref-width: 340px;
                    -fx-min-width: 280px;
                    -fx-padding: 16px;
                }

                .toast-success {
                    -fx-border-color: %s transparent transparent transparent;
                    -fx-border-width: 0 0 0 4px;
                    -fx-border-radius: 0 8px 8px 0;
                }

                .toast-warning {
                    -fx-border-color: transparent transparent transparent %s;
                    -fx-border-width: 0 0 0 4px;
                    -fx-border-radius: 0 8px 8px 0;
                }

                .toast-error {
                    -fx-border-color: transparent transparent transparent %s;
                    -fx-border-width: 0 0 0 4px;
                    -fx-border-radius: 0 8px 8px 0;
                }

                .toast-info {
                    -fx-border-color: transparent transparent transparent %s;
                    -fx-border-width: 0 0 0 4px;
                    -fx-border-radius: 0 8px 8px 0;
                }

                .toast-title {
                    -fx-font-size: 14px;
                    -fx-font-weight: bold;
                    -fx-text-fill: %s;
                }

                .toast-message {
                    -fx-font-size: 13px;
                    -fx-text-fill: %s;
                    -fx-wrap-text: true;
                }

                /* ----------------------------------------------------------
                   SEPARATOR / DIVIDER
                   ---------------------------------------------------------- */
                .separator {
                    -fx-background-color: %s;
                }

                /* ----------------------------------------------------------
                   SCROLL BARS
                   ---------------------------------------------------------- */
                .scroll-bar:vertical .thumb,
                .scroll-bar:horizontal .thumb {
                    -fx-background-color: %s;
                    -fx-background-radius: 4px;
                }

                .scroll-bar:vertical .thumb:hover,
                .scroll-bar:horizontal .thumb:hover {
                    -fx-background-color: %s;
                }

                .scroll-bar .track {
                    -fx-background-color: %s;
                }

                .scroll-bar .increment-button,
                .scroll-bar .decrement-button {
                    -fx-background-color: transparent;
                    -fx-opacity: 0;
                }

                /* ----------------------------------------------------------
                   TAB PANE
                   ---------------------------------------------------------- */
                .tab-pane .tab-header-area .tab-header-background {
                    -fx-background-color: %s;
                    -fx-border-color: transparent transparent %s transparent;
                    -fx-border-width: 0 0 1px 0;
                }

                .tab-pane .tab {
                    -fx-background-color: transparent;
                    -fx-text-fill: %s;
                    -fx-font-size: 14px;
                    -fx-padding: 10px 16px;
                }

                .tab-pane .tab:selected {
                    -fx-background-color: transparent;
                    -fx-text-fill: %s;
                    -fx-font-weight: bold;
                    -fx-border-color: transparent transparent %s transparent;
                    -fx-border-width: 0 0 2px 0;
                }

                .tab-pane .tab:hover {
                    -fx-text-fill: %s;
                }
                """.formatted(
                // root
                n100,
                // sidebar
                p900, p900,
                // sidebar section label
                n500,
                // nav items
                p800, p800, p400,
                // topbar
                n000, n300, n500, n900,
                // global search
                n000, n300, n900, n500, p600,
                // content area
                n100, n900, n700,
                // card
                n000, n300,
                // kpi card
                n000, n300, n500, n900, succ600, dang600,
                // btn-primary
                p700, p600, p800, n300, n500,
                // btn-secondary
                p700, p700, p050,
                // btn-danger
                dang600,
                // btn-icon
                n700, n100,
                // form
                n700, n000, n300, n900, n500, p600, dang600, dang600,
                // form-combo
                n000, n300, p600,
                // data table
                n000, n300, n100, n700, n100,
                n000, n300, p050, p100, p100, n300, p400,
                n900,
                // badges
                succ100, succ600, warn100, warn600, info100, info600,
                dang100, dang600, n100, n500, succ100, succ600, n100, n500,
                // modal
                n000, n300, n900, n300,
                // toast
                n000, succ600, warn600, dang600, info600, n900, n700,
                // separator
                n300,
                // scrollbar
                n300, n500, n100,
                // tab pane
                n000, n300, n500, p700, p700, p600
        );
    }
}
