package com.logistics.app;

import com.logistics.infrastructure.adapter.ServiceLocator;
import com.logistics.ui.components.NotificationToast;
import com.logistics.ui.components.SidebarNav;
import com.logistics.ui.components.TopBar;
import com.logistics.ui.screens.*;
import com.logistics.ui.theme.AppStylesheet;
import com.logistics.ui.theme.DesignTokens;
import javafx.animation.FadeTransition;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.layout.*;
import javafx.stage.Stage;
import javafx.util.Duration;

/**
 * Application entry point.
 *
 * Architecture:
 *   MainApplication (JavaFX Application)
 *     └─ Scene
 *          └─ rootStack (StackPane)
 *               ├─ LoginScreen     (shown first, covers entire scene)
 *               └─ appShell (BorderPane — visible after login)
 *                    ├─ left:   SidebarNav
 *                    ├─ top:    TopBar
 *                    └─ center: contentArea (StackPane — holds current screen)
 *
 * Navigation:
 *   SidebarNav fires Screen enum values via setOnNavigate().
 *   navigateTo(Screen) fades out the current screen, swaps it, fades in the new one.
 *
 * Stylesheet:
 *   A single CSS stylesheet is generated by AppStylesheet.toDataUri() and applied
 *   to the Scene. All components use style classes defined in that stylesheet.
 *
 * Toast notifications:
 *   A NotificationToast.ToastHost is stacked above the app shell so toasts
 *   always render on top of all content.
 */
public class MainApplication extends Application {

    // -------------------------------------------------------------------------
    // Layout roots
    // -------------------------------------------------------------------------

    private final StackPane   rootStack   = new StackPane();
    private final BorderPane  appShell    = new BorderPane();
    private final StackPane   contentArea = new StackPane();

    // -------------------------------------------------------------------------
    // Navigation components
    // -------------------------------------------------------------------------

    private final SidebarNav  sidebar     = new SidebarNav();
    private final TopBar      topBar      = new TopBar();

    // -------------------------------------------------------------------------
    // Screens (lazy-initialised on first navigation)
    // -------------------------------------------------------------------------

    private DashboardScreen    dashboardScreen;
    private CompanyListScreen  companyListScreen;
    private LocationListScreen locationListScreen;
    private BarycentreScreen   barycentreScreen;

    // -------------------------------------------------------------------------
    // JavaFX lifecycle
    // -------------------------------------------------------------------------

    @Override
    public void start(Stage primaryStage) {
        // Initialise the service layer and seed sample data before building the UI
        ServiceLocator.getInstance();

        buildSidebar();
        buildAppShell();

        // Toast notification host (top-most layer)
        NotificationToast.ToastHost toastHost = new NotificationToast.ToastHost();
        NotificationToast.setHost(toastHost);

        // Login screen
        LoginScreen loginScreen = buildLoginScreen();

        rootStack.getChildren().addAll(appShell, loginScreen, toastHost);

        // Apply the master stylesheet to the scene
        Scene scene = new Scene(rootStack,
                DesignTokens.WINDOW_DEFAULT_WIDTH,
                DesignTokens.WINDOW_DEFAULT_HEIGHT);
        scene.getStylesheets().add(AppStylesheet.toDataUri());

        primaryStage.setTitle("Define Company Logistics Platform");
        primaryStage.setMinWidth(DesignTokens.WINDOW_MIN_WIDTH);
        primaryStage.setMinHeight(DesignTokens.WINDOW_MIN_HEIGHT);
        primaryStage.setScene(scene);
        primaryStage.show();

        // Start on the login screen
        appShell.setVisible(false);
    }

    // -------------------------------------------------------------------------
    // Shell construction
    // -------------------------------------------------------------------------

    private void buildSidebar() {
        sidebar.addSection("MAIN");
        sidebar.addItem(new SidebarNav.NavItem("Dashboard",  "view-dashboard",   SidebarNav.Screen.DASHBOARD));

        sidebar.addSection("MANAGEMENT");
        sidebar.addItem(new SidebarNav.NavItem("Companies",  "domain",           SidebarNav.Screen.COMPANIES));
        sidebar.addItem(new SidebarNav.NavItem("Locations",  "map-marker",       SidebarNav.Screen.LOCATIONS));
        sidebar.addItem(new SidebarNav.NavItem("Shipments",  "truck-delivery",   SidebarNav.Screen.SHIPMENTS));
        sidebar.addItem(new SidebarNav.NavItem("Routes",     "routes",           SidebarNav.Screen.ROUTES));
        sidebar.addItem(new SidebarNav.NavItem("Warehouses", "warehouse",        SidebarNav.Screen.WAREHOUSES));

        sidebar.addSection("ANALYTICS");
        sidebar.addItem(new SidebarNav.NavItem("Barycenter", "crosshairs-gps",   SidebarNav.Screen.REPORTS));
        sidebar.addItem(new SidebarNav.NavItem("Reports",    "chart-bar",        SidebarNav.Screen.REPORTS));

        sidebar.addSection("SYSTEM");
        sidebar.addItem(new SidebarNav.NavItem("Settings",   "cog",              SidebarNav.Screen.SETTINGS));

        sidebar.setOnNavigate(this::navigateTo);
    }

    private void buildAppShell() {
        topBar.setOnSearch(query ->
                NotificationToast.show("Search",
                        "Searching for: " + query,
                        NotificationToast.Type.INFO)
        );
        topBar.setUserInitials("JD");

        appShell.setLeft(sidebar);
        appShell.setTop(topBar);
        appShell.setCenter(contentArea);

        contentArea.setStyle("-fx-background-color: " + DesignTokens.CSS_NEUTRAL_100 + ";");
    }

    private LoginScreen buildLoginScreen() {
        LoginScreen loginScreen = new LoginScreen();
        loginScreen.setOnLogin((email, password) -> {
            // Simulate authentication — replace with real auth service call.
            if (email.contains("@") && !password.isBlank()) {
                loginScreen.loginSuccess();
                transitionToApp(loginScreen);
            } else {
                loginScreen.loginFailure("Invalid email or password. Please try again.");
            }
        });
        return loginScreen;
    }

    // -------------------------------------------------------------------------
    // Screen navigation
    // -------------------------------------------------------------------------

    /**
     * Navigates to the given screen with a fade transition.
     * Screens are created on first use and cached afterwards.
     *
     * @param screen the target screen
     */
    private void navigateTo(SidebarNav.Screen screen) {
        Region nextScreen = resolveScreen(screen);
        if (nextScreen == null) return;

        updateTopBar(screen);

        // Fade out current content, swap, fade in
        if (contentArea.getChildren().isEmpty()) {
            contentArea.getChildren().add(nextScreen);
            return;
        }

        javafx.scene.Node current = contentArea.getChildren().get(0);
        if (current == nextScreen) return;

        FadeTransition fadeOut = new FadeTransition(
                Duration.millis(DesignTokens.ANIM_PAGE_TRANSITION), current);
        fadeOut.setToValue(0);
        fadeOut.setOnFinished(e -> {
            contentArea.getChildren().setAll(nextScreen);
            nextScreen.setOpacity(0);
            FadeTransition fadeIn = new FadeTransition(
                    Duration.millis(DesignTokens.ANIM_PAGE_TRANSITION), nextScreen);
            fadeIn.setToValue(1);
            fadeIn.play();
        });
        fadeOut.play();
    }

    private Region resolveScreen(SidebarNav.Screen screen) {
        return switch (screen) {
            case DASHBOARD -> {
                if (dashboardScreen == null) dashboardScreen = new DashboardScreen();
                yield dashboardScreen;
            }
            case COMPANIES -> {
                if (companyListScreen == null) {
                    companyListScreen = new CompanyListScreen();
                    companyListScreen.setOnAddCompany(() ->
                            NotificationToast.show("Add Company",
                                    "Company form dialog would open here.",
                                    NotificationToast.Type.INFO));
                }
                yield companyListScreen;
            }
            case LOCATIONS -> {
                if (locationListScreen == null) {
                    locationListScreen = new LocationListScreen();
                    locationListScreen.setOnAddLocation(() ->
                            NotificationToast.show("Add Location",
                                    "Location form dialog would open here.",
                                    NotificationToast.Type.INFO));
                }
                yield locationListScreen;
            }
            case REPORTS -> {
                if (barycentreScreen == null) barycentreScreen = new BarycentreScreen();
                yield barycentreScreen;
            }
            // Placeholder for screens not yet implemented
            default -> buildPlaceholderScreen(screen.name());
        };
    }

    private void updateTopBar(SidebarNav.Screen screen) {
        String screenName = switch (screen) {
            case DASHBOARD  -> "Dashboard";
            case COMPANIES  -> "Companies";
            case LOCATIONS  -> "Locations";
            case SHIPMENTS  -> "Shipments";
            case ROUTES     -> "Routes";
            case WAREHOUSES -> "Warehouses";
            case REPORTS    -> "Reports";
            case SETTINGS   -> "Settings";
        };
        topBar.setBreadcrumb("Home", screenName);
    }

    // -------------------------------------------------------------------------
    // Login → App transition
    // -------------------------------------------------------------------------

    private void transitionToApp(LoginScreen loginScreen) {
        appShell.setVisible(true);
        appShell.setOpacity(0);

        FadeTransition fadeOutLogin = new FadeTransition(Duration.millis(300), loginScreen);
        fadeOutLogin.setToValue(0);
        fadeOutLogin.setOnFinished(e -> {
            rootStack.getChildren().remove(loginScreen);
            navigateTo(SidebarNav.Screen.DASHBOARD);

            FadeTransition fadeInApp = new FadeTransition(Duration.millis(300), appShell);
            fadeInApp.setToValue(1);
            fadeInApp.play();

            NotificationToast.show("Welcome back", "You are now signed in.", NotificationToast.Type.SUCCESS);
        });
        fadeOutLogin.play();
    }

    // -------------------------------------------------------------------------
    // Placeholder for unimplemented screens
    // -------------------------------------------------------------------------

    private Region buildPlaceholderScreen(String screenName) {
        javafx.scene.control.Label label = new javafx.scene.control.Label(
                screenName + " screen — implementation pending.");
        label.setStyle("-fx-font-size: 16px; -fx-text-fill: " + DesignTokens.CSS_NEUTRAL_500 + ";");

        VBox box = new VBox(label);
        box.getStyleClass().add("content-area");
        box.setAlignment(javafx.geometry.Pos.CENTER);
        return box;
    }

    // -------------------------------------------------------------------------
    // Main
    // -------------------------------------------------------------------------

    public static void main(String[] args) {
        launch(args);
    }
}
